# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: MBI CD

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build:all
      - name: Extract tag or SHA
        id: tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          fi
      - name: Check if PR was merged
        id: merged
        if: github.event_name == 'pull_request'
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "PR was merged, proceeding with build"
            echo "CONTINUE=true" >> $GITHUB_OUTPUT
          else
            echo "PR was closed without merging, skipping build"
            echo "CONTINUE=false" >> $GITHUB_OUTPUT
          fi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: ${{ github.event_name != 'pull_request' || steps.merged.outputs.CONTINUE == 'true' }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name != 'pull_request' || steps.merged.outputs.CONTINUE == 'true' }}

      - name: Get lowercase repository owner
        id: repo_owner
        run: |
          echo "OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.repo_owner.outputs.OWNER }}/${{ github.event.repository.name }}:${{ steps.tag.outputs.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        if: ${{ github.event_name != 'pull_request' || steps.merged.outputs.CONTINUE == 'true' }}
